//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFCinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDM_FuncionHoraSilla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FDM_FuncionHoraSilla()
        {
            this.FDM_Reserva = new HashSet<FDM_Reserva>();
        }
    
        public decimal FHS_Funcion_ID { get; set; }
        public System.DateTime FHS_Fecha { get; set; }
        public System.TimeSpan FHS_Hora { get; set; }
        public decimal FHS_Silla { get; set; }
        public decimal FHS_Reservada { get; set; }
    
        public virtual FDM_FuncionHora FDM_FuncionHora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDM_Reserva> FDM_Reserva { get; set; }
    }
}
