//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFCinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDM_Reserva
    {
        public decimal R_Funcion_ID { get; set; }
        public System.DateTime R_Fecha { get; set; }
        public System.TimeSpan R_Hora { get; set; }
        public decimal R_Silla { get; set; }
        public string R_DocumentoPersona { get; set; }
        public string R_NombrePersona { get; set; }
        public string R_TelefonoPersona { get; set; }
        public decimal R_ValorPagado { get; set; }
        public System.DateTime R_FechaReserva { get; set; }
    
        public virtual FDM_FuncionHoraSilla FDM_FuncionHoraSilla { get; set; }
    }
}
