//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFCinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDM_FuncionHora
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FDM_FuncionHora()
        {
            this.FDM_FuncionHoraSilla = new HashSet<FDM_FuncionHoraSilla>();
        }
    
        public decimal HF_Funcion_ID { get; set; }
        public System.DateTime HF_Fecha { get; set; }
        public System.TimeSpan HF_Hora { get; set; }
        public decimal HF_Descuento { get; set; }
        public decimal HF_PorcentajeDescuento { get; set; }
    
        public virtual FDM_Funcion FDM_Funcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDM_FuncionHoraSilla> FDM_FuncionHoraSilla { get; set; }
    }
}
